/**
 * Header file for the Check model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Check/ChckHorCalc.h"
#include "Check/ChkVerCalc.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace JIWY { namespace Check { 

class Check : public Parallel
{

public:
  // Define constructor and destructor
  Check(ChannelOut<double> *hor_check_in, ChannelIn<uint16_t> *hor_robot_out, ChannelOut<double> *vert_check_in, ChannelIn<uint16_t> *vert_robot_out);
  virtual ~Check();

private:

  // Class variables
  double hor_in;
  uint16_t hor_out;
  double ver_in;
  uint16_t ver_out;

  // Model objects
  ChckHorCalc::ChckHorCalc *myChckHorCalc;
  ChkVerCalc::ChkVerCalc *myChkVerCalc;
  Writer<uint16_t> *myhor_out_writer;
  Reader<double> *myhorizontal_horchk_reader;
  Writer<uint16_t> *myver_out_writer;
  Reader<double> *myvertical_verticalchk_reader;

  // Model groups
  Sequential *mySEQUENTIAL;
  Sequential *mySEQUENTIAL1;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
