/**
 * Header file for the JIWY model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Check.h"
#include "PositionControllerPan/PositionControllerPan.h"
#include "PositionControllerTilt/PositionControllerTilt.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace JIWY { 

class JIWY : public Parallel
{

public:
  // Define constructor and destructor
  JIWY(ChannelOut<uint32_t> *joystick_hor_in, ChannelOut<uint32_t> *joystick_vert_in, ChannelOut<uint32_t> *robot_hor_feedback, ChannelIn<uint16_t> *robot_hor_out, ChannelOut<uint32_t> *robot_ver_feedback, ChannelIn<uint16_t> *robot_ver_out);
  virtual ~JIWY();

private:

  // Class variables
  uint16_t Test;

  // Channel definitions
  UnbufferedChannel<uint32_t, One2In, Out2One> *myHorizontalcorr_to_VerticalcorrChannel;
  UnbufferedChannel<uint32_t, One2In, Out2One> *myHorizontalout_to_Checkhor_check_inChannel;
  UnbufferedChannel<uint32_t, One2In, Out2One> *myVerticalout_to_Checkvert_check_inChannel;

  // Model objects
  Check::Check *myCheck;
  PositionControllerPan::PositionControllerPan *myHorizontal;
  PositionControllerTilt::PositionControllerTilt *myVertical;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
