/**
 * Source file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.0
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "MainModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
#include <hw/inout.h>
#include <sys/neutrino.h>
// protected region additional headers end

namespace MainModel { 

MainModel::MainModel() :
    Recursion<CSProcess>()
{
  SETNAME(this, "MainModel");

  // Initialize hardware channels
  AnyIO::AnyioPWMSettings myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings;
  myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings.deviceNr = 0;
  myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings.pwmNr = 0;
  myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings.interlaced = false;
  myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings.bridge_type = 0; //Bert H-Bridge 
  myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings.baseAddress = 0x30;
  myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings.registerSize = 2;
  myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings.baseControlAddress = 0x40;
  myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings.controlRegisterSize = 2;
  myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings.gModeAddress = 0x52;
  myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings.pwmEnableBit = 1;
  myJIWYrobot_hor_out_to_robot_pwm_horChannel = new AnyIO::AnyioPWMLinkDriver(myJIWYrobot_hor_out_to_robot_pwm_horChannelSettings);

  AnyIO::AnyioPWMSettings myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings;
  myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings.deviceNr = 0;
  myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings.pwmNr = 0;
  myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings.interlaced = false;
  myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings.bridge_type = 0; //Bert H-Bridge 
  myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings.baseAddress = 0x30;
  myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings.registerSize = 2;
  myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings.baseControlAddress = 0x40;
  myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings.controlRegisterSize = 2;
  myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings.gModeAddress = 0x52;
  myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings.pwmEnableBit = 1;
  myJIWYrobot_ver_out_to_robot_pwm_vertChannel = new AnyIO::AnyioPWMLinkDriver(myJIWYrobot_ver_out_to_robot_pwm_vertChannelSettings);

  AnyIO::AnyioEncoderSettings myencoder_hor_feedback_to_JIWYjoystick_hor_inChannelSettings;
  myencoder_hor_feedback_to_JIWYjoystick_hor_inChannelSettings.deviceNr = 0;
  myencoder_hor_feedback_to_JIWYjoystick_hor_inChannelSettings.encoderNr = 0;
  myencoder_hor_feedback_to_JIWYjoystick_hor_inChannelSettings.baseAddress = 0x0;
  myencoder_hor_feedback_to_JIWYjoystick_hor_inChannelSettings.registerSize = 4;
  myencoder_hor_feedback_to_JIWYjoystick_hor_inChannelSettings.baseControlAddress = 0x20;
  myencoder_hor_feedback_to_JIWYjoystick_hor_inChannelSettings.controlRegisterSize = 2;
  myencoder_hor_feedback_to_JIWYjoystick_hor_inChannelSettings.gModeAddress = 0x52;
  myencoder_hor_feedback_to_JIWYjoystick_hor_inChannelSettings.encoderEnableBit = 0;
  myencoder_hor_feedback_to_JIWYjoystick_hor_inChannel = new AnyIO::AnyioEncoderLinkDriver<uint32_t>(myencoder_hor_feedback_to_JIWYjoystick_hor_inChannelSettings);

  AnyIO::AnyioEncoderSettings myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannelSettings;
  myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannelSettings.deviceNr = 0;
  myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannelSettings.encoderNr = 0;
  myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannelSettings.baseAddress = 0x0;
  myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannelSettings.registerSize = 4;
  myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannelSettings.baseControlAddress = 0x20;
  myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannelSettings.controlRegisterSize = 2;
  myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannelSettings.gModeAddress = 0x52;
  myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannelSettings.encoderEnableBit = 0;
  myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannel = new AnyIO::AnyioEncoderLinkDriver<uint32_t>(myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannelSettings);

  AnyIO::AnyioEncoderSettings myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannelSettings;
  myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannelSettings.deviceNr = 0;
  myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannelSettings.encoderNr = 0;
  myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannelSettings.baseAddress = 0x0;
  myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannelSettings.registerSize = 4;
  myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannelSettings.baseControlAddress = 0x20;
  myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannelSettings.controlRegisterSize = 2;
  myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannelSettings.gModeAddress = 0x52;
  myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannelSettings.encoderEnableBit = 0;
  myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannel = new AnyIO::AnyioEncoderLinkDriver<uint32_t>(myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannelSettings);

  AnyIO::AnyioEncoderSettings myencoder_vert_feedback_to_JIWYjoystick_vert_inChannelSettings;
  myencoder_vert_feedback_to_JIWYjoystick_vert_inChannelSettings.deviceNr = 0;
  myencoder_vert_feedback_to_JIWYjoystick_vert_inChannelSettings.encoderNr = 0;
  myencoder_vert_feedback_to_JIWYjoystick_vert_inChannelSettings.baseAddress = 0x0;
  myencoder_vert_feedback_to_JIWYjoystick_vert_inChannelSettings.registerSize = 4;
  myencoder_vert_feedback_to_JIWYjoystick_vert_inChannelSettings.baseControlAddress = 0x20;
  myencoder_vert_feedback_to_JIWYjoystick_vert_inChannelSettings.controlRegisterSize = 2;
  myencoder_vert_feedback_to_JIWYjoystick_vert_inChannelSettings.gModeAddress = 0x52;
  myencoder_vert_feedback_to_JIWYjoystick_vert_inChannelSettings.encoderEnableBit = 0;
  myencoder_vert_feedback_to_JIWYjoystick_vert_inChannel = new AnyIO::AnyioEncoderLinkDriver<uint32_t>(myencoder_vert_feedback_to_JIWYjoystick_vert_inChannelSettings);

  // Initialize model objects
  myJIWY = new JIWY::JIWY(myencoder_hor_feedback_to_JIWYjoystick_hor_inChannel, myencoder_vert_feedback_to_JIWYjoystick_vert_inChannel, myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannel, myJIWYrobot_hor_out_to_robot_pwm_horChannel, myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannel, myJIWYrobot_ver_out_to_robot_pwm_vertChannel);
  SETNAME(myJIWY, "JIWY");

  // Create Parallel group containing all architecture components
  parallelGroup = new Parallel(
    (CSPConstruct *) myJIWY,
    NULL
  );
  SETNAME(parallelGroup, "parallelGroup");

  // Register group as top-level recursive object
  setToActivate(parallelGroup);
  setEvaluateCondition(true);
}

MainModel::~MainModel()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // Destroy model objects
  delete myJIWY;

  // Destroy channels
  delete myJIWYrobot_hor_out_to_robot_pwm_horChannel;
  delete myJIWYrobot_ver_out_to_robot_pwm_vertChannel;
  delete myencoder_hor_feedback_to_JIWYjoystick_hor_inChannel;
  delete myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannel;
  delete myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannel;
  delete myencoder_vert_feedback_to_JIWYjoystick_vert_inChannel;
}

// Close namespace(s)
} 
