/**
 * Source file for the EncoderTester model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "EncoderTester.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace EncoderTester { 

EncoderTester::EncoderTester(ChannelOut<uint32_t> *in) :
    Sequential(NULL)
{
  SETNAME(this, "EncoderTester");

  // Initialize model objects
  myPcode = new Pcode::Pcode(test);
  SETNAME(myPcode, "Pcode");
  myreader = new Reader<uint32_t>(&test, in);
  SETNAME(myreader, "reader");


  // Register model objects
  this->append_child(myreader);
  this->append_child(myPcode);

  // protected region constructor on begin
  // protected region constructor end
}

EncoderTester::~EncoderTester()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model objects
  delete myreader;
  delete myPcode;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
