/**
 * Source file for the MainModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "MainModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { 



MainModel::MainModel() :
    Parallel(NULL)
{
  SETNAME(this, "MainModel");

  // Initialize channels
  myProducer12prod_ch1_to_Consumer12cons_ch1Channel = new UnbufferedChannel<int, One2In, Out2One>();
  myProducer12prod_ch2_to_Consumer12cons_ch2Channel = new UnbufferedChannel<int, One2In, Out2One>();

  // Initialize model objects
  myConsumer12 = new Consumer12::Consumer12(myProducer12prod_ch1_to_Consumer12cons_ch1Channel, myProducer12prod_ch2_to_Consumer12cons_ch2Channel);
  SETNAME(myConsumer12, "Consumer12");
  myProducer12 = new Producer12::Producer12(myProducer12prod_ch1_to_Consumer12cons_ch1Channel, myProducer12prod_ch2_to_Consumer12cons_ch2Channel);
  SETNAME(myProducer12, "Producer12");


  // Register model objects
  this->append_child(myProducer12);
  this->append_child(myConsumer12);

  // protected region constructor on begin
  // protected region constructor end
}

MainModel::~MainModel()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model objects
  delete myProducer12;
  delete myConsumer12;

  // Destroy channels
  delete myProducer12prod_ch1_to_Consumer12cons_ch1Channel;
  delete myProducer12prod_ch2_to_Consumer12cons_ch2Channel;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
