/**
 * Source file for the Producer12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Producer12.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Producer12 { 



Producer12::Producer12(ChannelIn<int> *prod_ch1, ChannelIn<int> *prod_ch2) :
    Recursion<CSPConstruct>()
{
  SETNAME(this, "Producer12");

  // Initialize model objects
  myPCode = new PCode::PCode(anotherValue, someValue);
  SETNAME(myPCode, "PCode");
  mych1write = new Writer<int>(&someValue, prod_ch1);
  SETNAME(mych1write, "ch1write");
  mych2write = new Writer<int>(&anotherValue, prod_ch2);
  SETNAME(mych2write, "ch2write");

  // Create SEQUENTIAL_B group
  mySEQUENTIAL_B = new Sequential(
    (CSPConstruct *) mych1write,
    (CSPConstruct *) mych2write,
    NULL
  );
  SETNAME(mySEQUENTIAL_B, "SEQUENTIAL_B");

  // Create SEQUENTIAL_A group
  mySEQUENTIAL_A = new Sequential(
    (CSPConstruct *) myPCode,
    (CSPConstruct *) mySEQUENTIAL_B,
    NULL
  );
  SETNAME(mySEQUENTIAL_A, "SEQUENTIAL_A");

  // Register SEQUENTIAL_A as top-level recursive object
  setToActivate(mySEQUENTIAL_A);
  setEvaluateCondition(true);


  // protected region constructor on begin
  // protected region constructor end
}

Producer12::~Producer12()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete mySEQUENTIAL_A;
  delete mySEQUENTIAL_B;

  // Destroy model objects
  delete mych2write;
  delete mych1write;
  delete myPCode;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
