/**
 * Header file for the PWMTester model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Pcode.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace PWMTester { 

class PWMTester : public Sequential
{

public:
  // Define constructor and destructor
  PWMTester(ChannelIn<uint16_t> *pwmport);
  virtual ~PWMTester();

private:

  // Class variables
  uint16_t test;

  // Model objects
  Pcode::Pcode *myPcode;
  Writer<uint16_t> *mypwmwriter;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
