# build.mk file for overview.archm, provide information to 'project MakeFile' 
# Generated by the TERRA Arch2LUNA generator version 1.0.0
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/overview

overview/overview:
	@echo
	@echo "Building $@"
	@make -C overview --no-print-directory

bin/overview: overview/overview | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/overview gets properly rebuild
overview/overview: overview/src/main.cpp JIWY/lib/libJIWY.a Joystick/lib/libJoystick.a Encoder_convert/lib/libEncoder_convert.a Encoder_convert/lib/libEncoder_convert.a PositionControllerPan/lib/libPositionControllerPan.a PositionControllerTilt/lib/libPositionControllerTilt.a Encoder_vert/lib/libEncoder_vert.a
overview/overview: overview/src/MainModel.cpp overview/include/MainModel.h Encoder_convert/include/Encoder_convert/Encoder_convert.h Encoder_convert/include/Encoder_convert/Encoder_convert.h JIWY/include/JIWY/JIWY.h Joystick/include/Joystick/Joystick.h PositionControllerTilt/include/PositionControllerTilt/PositionControllerTilt.h PositionControllerPan/include/PositionControllerPan/PositionControllerPan.h Encoder_vert/include/Encoder_vert/Encoder_vert.h

# protected region additional dependencies on begin
# protected region additional dependencies end