/**
 * Header file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.0
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Hardware Channels
#include "anyio/AnyioEncoderLinkDriver.h"
#include "anyio/AnyioPWMLinkDriver.h"

// Models
#include "JIWY/JIWY.h"

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Recursion<CSProcess>
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  AnyIO::AnyioPWMLinkDriver *myJIWYrobot_hor_out_to_robot_pwm_horChannel;
  AnyIO::AnyioPWMLinkDriver *myJIWYrobot_ver_out_to_robot_pwm_vertChannel;
  AnyIO::AnyioEncoderLinkDriver<uint32_t> *myencoder_hor_feedback_to_JIWYjoystick_hor_inChannel;
  AnyIO::AnyioEncoderLinkDriver<uint32_t> *myencoder_hor_robot_to_JIWYrobot_hor_feedbackChannel;
  AnyIO::AnyioEncoderLinkDriver<uint32_t> *myencoder_ver_robot_to_JIWYrobot_ver_feedbackChannel;
  AnyIO::AnyioEncoderLinkDriver<uint32_t> *myencoder_vert_feedback_to_JIWYjoystick_vert_inChannel;

  // Model objects
  JIWY::JIWY *myJIWY;

  // Model groups
  Parallel *parallelGroup;
};

// Close namespace(s)
} 
