/**
 * Header file for the MainModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Consumer12.h"
#include "Producer12.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public PriParallel
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();



private:

  // Channel definitions
  UnbufferedChannel<bool, One2In, Out2One> *myProducer12prod_ch1_to_Consumer12cons_ch1Channel;

  // Model objects
  Consumer12::Consumer12 *myConsumer12;
  Producer12::Producer12 *myProducer12;

  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
