/**
 * Header file for the Producer12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Producer12 { 

class Producer12 : public Sequential
{

public:
  // Define constructor and destructor
  Producer12(ChannelIn<bool> *prod_ch1);
  virtual ~Producer12();



private:

  // Class variables
  bool anotherValue;
  bool someValue;

  // Model objects
  Writer<bool> *mych1write;

  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
