/**
 * Header file for the x_code model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional h1eader should get a corresponding dependency in the Makefile

#include "hid/HID.h"
// protected region additional headers end

using namespace LUNA::CSP;

namespace Joystick { namespace x_code { 

class x_code : public CodeBlock
{

public:
  // Define constructor and destructor
  x_code(double &x);
  virtual ~x_code();

  void execute();

private:

  // Class variables
  double &x;

  // protected region additional class members or functions on begin
  bool btn;
  LUNA::CSP::HIDAbsAxisChannel *channel;
  LUNA::CSP::Reader<double> *reader;

  HIDButtonChannel *buttonchannel;
  LUNA::CSP::Reader<bool> *buttonreader;
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
