# build.mk file for timer.archm, provide information to 'project MakeFile' 
# Generated by the TERRA Arch2LUNA generator version 1.0.0
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/timer

timer/timer:
	@echo
	@echo "Building $@"
	@make -C timer --no-print-directory

bin/timer: timer/timer | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/timer gets properly rebuild
timer/timer: timer/src/main.cpp submodel/lib/libsubmodel.a
timer/timer: timer/src/MainModel.cpp timer/include/MainModel.h submodel/include/submodel/submodel.h

# protected region additional dependencies on begin
# protected region additional dependencies end