/**
 * Header file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.0
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Hardware Channels
#include "anyio/AnyioEncoderLinkDriverSim.h"

// Models
#include "encodertestersubmodel/encodertestersubmodel.h"

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Recursion<CSProcess>
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  AnyIO::AnyioEncoderLinkDriverSim<uint32_t> *myEncoderTesterport_to_encoderportChannel;

  // Model objects
  encodertestersubmodel::encodertestersubmodel *myEncoderTester;

  // Model groups
  Parallel *parallelGroup;
};

// Close namespace(s)
} 
