# build.mk file for Encoder_vert.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libEncoder_vert.a

Encoder_vert/lib/libEncoder_vert.a:
	@echo
	@echo "Building $@"
	@make -C Encoder_vert --no-print-directory

lib/libEncoder_vert.a: Encoder_vert/lib/libEncoder_vert.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libEncoder_vert.a gets properly rebuild
Encoder_vert/lib/libEncoder_vert.a: Encoder_vert/src/Encoder_vert.cpp Encoder_vert/include/Encoder_vert/Encoder_vert.h
Encoder_vert/lib/libEncoder_vert.a: Encoder_vert/src/encodervert.cpp Encoder_vert/include/Encoder_vert/encodervert.h

# protected region additional dependencies on begin
# protected region additional dependencies end