/**
 * Header file for the Producer12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Producer12/PCode.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Producer12 { 

class Producer12 : public Recursion<CSPConstruct>
{

public:
  // Define constructor and destructor
  Producer12(ChannelIn<int> *prod_ch1, ChannelIn<int> *prod_ch2);
  virtual ~Producer12();



private:

  // Class variables
  int anotherValue;
  int someValue;

  // Model objects
  PCode::PCode *myPCode;
  Writer<int> *mych1write;
  Writer<int> *mych2write;

  // Model groups
  Sequential *mySEQUENTIAL_A;
  Sequential *mySEQUENTIAL_B;

  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
