/**
 * Header file for the hor_convert model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace IO { namespace hor_convert { 

class hor_convert : public CodeBlock
{

public:
  // Define constructor and destructor
  hor_convert(double &hor_input, uint16_t &hor_output);
  virtual ~hor_convert();

  void execute();

private:

  // Class variables
  double &hor_input;
  uint16_t &hor_output;

  // protected region additional class members or functions on begin
  uint16_t convert(double f);
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
