/**
 * Header file for the IO model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "hor_convert.h"
#include "ver_convert.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace IO { 

class IO : public Parallel
{

public:
  // Define constructor and destructor
  IO(ChannelOut<double> *horin, ChannelIn<uint16_t> *horout, ChannelOut<double> *verin, ChannelIn<uint16_t> *verout);
  virtual ~IO();

private:

  // Class variables
  double hor_input;
  uint16_t hor_output;
  double ver_input;
  uint16_t ver_output;

  // Model objects
  hor_convert::hor_convert *myhor_convert;
  Reader<double> *myhorinpre;
  Writer<uint16_t> *myhoroutwr;
  ver_convert::ver_convert *myver_convert;
  Reader<double> *myverinre;
  Writer<uint16_t> *myveroutwr;

  // Model groups
  Sequential *mySEQUENTIAL;
  Sequential *mySEQUENTIAL1;



  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} 
