/**
 * Header file for the ver_convert model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace IO { namespace ver_convert { 

class ver_convert : public CodeBlock
{

public:
  // Define constructor and destructor
  ver_convert(double &ver_input, uint16_t &ver_output);
  virtual ~ver_convert();

  void execute();

private:

  // Class variables
  double &ver_input;
  uint16_t &ver_output;

  // protected region additional class members or functions on begin
  uint16_t convert(double f);
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
