/**
 * Header file for the PositionControllerTilt model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "XXPositionControllerTiltModel.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace PositionControllerTilt { 

class PositionControllerTilt : public Sequential
{

public:
  // Define constructor and destructor
  PositionControllerTilt(ChannelOut<uint32_t> *corr, ChannelOut<uint32_t> *in, ChannelIn<uint32_t> *out, ChannelOut<uint32_t> *position);
  virtual ~PositionControllerTilt();

private:

  // Class variables
  uint32_t v_corr;
  uint32_t v_in;
  uint32_t v_out;
  uint32_t v_position;

  // Model objects
  XXPositionControllerTiltModel::XXPositionControllerTiltModel *myXXPositionControllerTiltModel;
  Reader<uint32_t> *myr_corr;
  Reader<uint32_t> *myr_in;
  Reader<uint32_t> *myr_position;
  Writer<uint32_t> *myw_out;

  // Model groups
  Parallel *myINS;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
