# build.mk file for Joystick.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libJoystick.a

Joystick/lib/libJoystick.a:
	@echo
	@echo "Building $@"
	@make -C Joystick --no-print-directory

lib/libJoystick.a: Joystick/lib/libJoystick.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libJoystick.a gets properly rebuild
Joystick/lib/libJoystick.a: Joystick/src/Joystick.cpp Joystick/include/Joystick/Joystick.h
Joystick/lib/libJoystick.a: Joystick/src/x_code.cpp Joystick/include/Joystick/x_code.h
Joystick/lib/libJoystick.a: Joystick/src/y_code.cpp Joystick/include/Joystick/y_code.h

# protected region additional dependencies on begin
# protected region additional dependencies end