/**
 * Header file for the PositionControllerPan model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "XXPositionControllerPanModel.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace PositionControllerPan { 

class PositionControllerPan : public Sequential
{

public:
  // Define constructor and destructor
  PositionControllerPan(ChannelIn<double> *corr, ChannelOut<double> *in, ChannelIn<double> *out, ChannelOut<double> *position);
  virtual ~PositionControllerPan();

private:

  // Class variables
  double v_corr;
  double v_in;
  double v_out;
  double v_position;

  // Model objects
  XXPositionControllerPanModel::XXPositionControllerPanModel *myXXPositionControllerPanModel;
  Reader<double> *myr_in;
  Reader<double> *myr_position;
  Writer<double> *myw_corr;
  Writer<double> *myw_out;

  // Model groups
  Parallel *myINS;
  Parallel *myOUTS;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
