/**
 * Header file for the XXPositionControllerPanModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * 20-sim C++ glue code to connect to PositionControllerPanModel
 * Modifying this file is absolutely not recommended!
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
#include "xxsim/PositionControllerPanModel.hpp" 
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace PositionControllerPan { namespace XXPositionControllerPanModel { 

class XXPositionControllerPanModel : public CodeBlock
{

public:
  // Define constructor and destructor
  XXPositionControllerPanModel(uint32_t &corr, uint32_t &in, uint32_t &out, uint32_t &position);
  virtual ~XXPositionControllerPanModel();

  void execute();

private:

  // Class variables
  uint32_t &corr;
  uint32_t &in;
  uint32_t &out;
  uint32_t &position;

  PositionControllerPanModel *m_model;
};

// Close namespace(s)
} } 
