/**
 * Source file for the Pcode model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Pcode.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
#include <string.h>
#include <sys/time.h>
// protected region additional headers end

namespace submodel { namespace Pcode { 

Pcode::Pcode(LUNA::Clock::period_t &test) :
    CodeBlock(), test(test){
  SETNAME(this, "Pcode");

  // protected region constructor on begin
  // protected region constructor end
}

Pcode::~Pcode()
{
  // protected region destructor on begin
  // protected region destructor end
}

void Pcode::execute()
{
  // protected region execute code on begin
	static struct timespec t1;


	struct timespec t2;

	clock_gettime(CLOCK_REALTIME, &t2);
	//long int elapsedTime = (t2.tv_usec - t1.tv_usec);

	printf("%ld.%.9ld, %ld.%.9ld\n", t2.tv_sec, t2.tv_nsec, t1.tv_sec, t1.tv_nsec);

	t1 = t2;

	// protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
