/**
 * Header file for the ch1Code model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace consumer { namespace ch1Code { 

class ch1Code : public CodeBlock
{

public:
  // Define constructor and destructor
  ch1Code(int &appel);
  virtual ~ch1Code();

  void execute();

private:

  // Class variables
  int &appel;

  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
