/**
 * Header file for the ch3Code model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace consumer { namespace ch3Code { 

class ch3Code : public CodeBlock
{

public:
  // Define constructor and destructor
  ch3Code();
  virtual ~ch3Code();

  void execute();

private:
  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
