/**
 * Header file for the consumer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "consumer/ch1Code.h"
#include "consumer/ch2Code.h"
#include "consumer/ch3Code.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace consumer { 

class consumer : public Parallel
{

public:
  // Define constructor and destructor
  consumer(ChannelOut<int> *ch1, ChannelOut<int> *ch2, ChannelOut<int> *ch3);
  virtual ~consumer();



private:

  // Class variables
  int data;

  // Model objects
  ch1Code::ch1Code *mych1Code;
  ch2Code::ch2Code *mych2Code;
  ch3Code::ch3Code *mych3Code;
  Reader<int> *myr1;
  Reader<int> *myr2;
  Reader<int> *myr3;

  // Model groups
  Sequential *mySEQUENTIAL_C1;
  Sequential *mySEQUENTIAL_C2;
  Sequential *mySEQUENTIAL_C3;

  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
