/**
 * Header file for the Producer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Producer/PCode.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Producer { 

class Producer : public Sequential
{

public:
  // Define constructor and destructor
  Producer(ChannelIn<int> *ch1, ChannelIn<int> *ch2, ChannelIn<int> *ch3);
  virtual ~Producer();


  // Guard evaluation functions
  bool w1GuardEvaluate();
  bool w2GuardEvaluate();
  bool w3GuardEvaluate();

private:

  // Class variables
  int data;

  // Model objects
  PCode::PCode *myPCode;
  Writer<int> *myw1;
  Writer<int> *myw2;
  Writer<int> *myw3;

  // Model groups
  Alternative *myALTERNATIVE;

  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
