/**
 * Source file for the Joystick model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Joystick.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace Joystick { 

Joystick::Joystick(ChannelIn<double> *joystick_hor, ChannelIn<double> *joystick_ver) :
    Parallel(NULL)
{
  SETNAME(this, "Joystick");

  // Initialize model objects
  myx_code = new x_code::x_code(x);
  SETNAME(myx_code, "x_code");
  myx_writer = new Writer<double>(&x, joystick_hor);
  SETNAME(myx_writer, "x_writer");
  myy_code = new y_code::y_code(y);
  SETNAME(myy_code, "y_code");
  myy_writer = new Writer<double>(&y, joystick_ver);
  SETNAME(myy_writer, "y_writer");

  // Create SEQUENTIAL group
  mySEQUENTIAL = new Sequential(
    (CSPConstruct *) myx_code,
    (CSPConstruct *) myx_writer,
    NULL
  );
  SETNAME(mySEQUENTIAL, "SEQUENTIAL");

  // Create SEQUENTIAL1 group
  mySEQUENTIAL1 = new Sequential(
    (CSPConstruct *) myy_code,
    (CSPConstruct *) myy_writer,
    NULL
  );
  SETNAME(mySEQUENTIAL1, "SEQUENTIAL1");


  // Register model objects
  this->append_child(mySEQUENTIAL);
  this->append_child(mySEQUENTIAL1);

  // protected region constructor on begin
  // protected region constructor end
}

Joystick::~Joystick()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete mySEQUENTIAL;
  delete mySEQUENTIAL1;

  // Destroy model objects
  delete myy_writer;
  delete myy_code;
  delete myx_writer;
  delete myx_code;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
