/**
 * Header file for the convert_vert model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace IO { namespace convert_vert { 

class convert_vert : public CodeBlock
{

public:
  // Define constructor and destructor
  convert_vert(double &ver_input, uint16_t &ver_output);
  virtual ~convert_vert();

  void execute();

private:

  // Class variables
  double &ver_input;
  uint16_t &ver_output;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
