/**
 * Header file for the IO model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "convert_hor.h"
#include "convert_vert.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace IO { 

class IO : public Parallel
{

public:
  // Define constructor and destructor
  IO(ChannelOut<double> *hor_input, ChannelIn<uint16_t> *hor_output, ChannelOut<double> *ver_input, ChannelIn<uint16_t> *ver_output);
  virtual ~IO();

private:

  // Class variables
  double hor_input;
  uint16_t hor_output;
  double ver_input;
  uint16_t ver_output;

  // Model objects
  convert_hor::convert_hor *myconvert_hor;
  convert_vert::convert_vert *myconvert_vert;
  Reader<double> *myhor_input_reader;
  Writer<uint16_t> *myhor_output_writer;
  Reader<double> *myver_input_reader;
  Writer<uint16_t> *myver_output_writer;

  // Model groups
  Sequential *mySEQUENTIAL;
  Sequential *mySEQUENTIAL1;



  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} 
