/**
 * Source file for the PCode model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Producer/PCode.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Producer { namespace PCode { 

PCode::PCode(int &peer) :
    CodeBlock(), peer(peer){
  SETNAME(this, "PCode");

  // protected region constructor on begin

  // protected region constructor end
}

PCode::~PCode()
{
  // protected region destructor on begin

  // protected region destructor end
}

void PCode::execute()
{
  // protected region execute code on begin

  // protected region execute code end
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } } 
