/**
 * Source file for the Step model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Step.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace Step { 

Step::Step(ChannelIn<double> *output, ChannelIn<double> *writer_setpoint) :
    Sequential(NULL)
{
  SETNAME(this, "Step");

  // Initialize model objects
  myXXStepModel = new XXStepModel::XXStepModel(v_output);
  SETNAME(myXXStepModel, "XXStepModel");
  myw_output = new Writer<double>(&v_output, output);
  SETNAME(myw_output, "w_output");
  mywriter_d = new Writer<double>(&v_output, writer_setpoint);
  SETNAME(mywriter_d, "writer_d");

  // Create PARALLEL group
  myPARALLEL = new Parallel(
    (CSPConstruct *) myw_output,
    (CSPConstruct *) mywriter_d,
    NULL
  );
  SETNAME(myPARALLEL, "PARALLEL");


  // Register model objects
  this->append_child(myXXStepModel);
  this->append_child(myPARALLEL);

  // protected region constructor on begin
  // protected region constructor end
}

Step::~Step()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete myPARALLEL;

  // Destroy model objects
  delete mywriter_d;
  delete myw_output;
  delete myXXStepModel;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
