/**
 * Source file for the Check model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Check.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace JIWY { namespace Check { 

Check::Check(ChannelOut<double> *hor_check_in, ChannelIn<uint16_t> *hor_robot_out, ChannelOut<double> *vert_check_in, ChannelIn<uint16_t> *vert_robot_out) :
    Parallel(NULL)
{
  SETNAME(this, "Check");

  // Initialize model objects
  myChckHorCalc = new ChckHorCalc::ChckHorCalc(hor_in, hor_out);
  SETNAME(myChckHorCalc, "ChckHorCalc");
  myChkVerCalc = new ChkVerCalc::ChkVerCalc(ver_in, ver_out);
  SETNAME(myChkVerCalc, "ChkVerCalc");
  myhor_out_writer = new Writer<uint16_t>(&hor_out, hor_robot_out);
  SETNAME(myhor_out_writer, "hor_out_writer");
  myhorizontal_horchk_reader = new Reader<double>(&hor_in, hor_check_in);
  SETNAME(myhorizontal_horchk_reader, "horizontal_horchk_reader");
  myver_out_writer = new Writer<uint16_t>(&ver_out, vert_robot_out);
  SETNAME(myver_out_writer, "ver_out_writer");
  myvertical_verticalchk_reader = new Reader<double>(&ver_in, vert_check_in);
  SETNAME(myvertical_verticalchk_reader, "vertical_verticalchk_reader");

  // Create SEQUENTIAL group
  mySEQUENTIAL = new Sequential(
    (CSPConstruct *) myvertical_verticalchk_reader,
    (CSPConstruct *) myChkVerCalc,
    (CSPConstruct *) myver_out_writer,
    NULL
  );
  SETNAME(mySEQUENTIAL, "SEQUENTIAL");

  // Create SEQUENTIAL1 group
  mySEQUENTIAL1 = new Sequential(
    (CSPConstruct *) myhorizontal_horchk_reader,
    (CSPConstruct *) myChckHorCalc,
    (CSPConstruct *) myhor_out_writer,
    NULL
  );
  SETNAME(mySEQUENTIAL1, "SEQUENTIAL1");


  // Register model objects
  this->append_child(mySEQUENTIAL1);
  this->append_child(mySEQUENTIAL);

  // protected region constructor on begin
  // protected region constructor end
}

Check::~Check()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete mySEQUENTIAL;
  delete mySEQUENTIAL1;

  // Destroy model objects
  delete myvertical_verticalchk_reader;
  delete myver_out_writer;
  delete myhorizontal_horchk_reader;
  delete myhor_out_writer;
  delete myChkVerCalc;
  delete myChckHorCalc;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
