/**
 * Header file for the Step model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "XXStepModel.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace Step { 

class Step : public Sequential
{

public:
  // Define constructor and destructor
  Step(ChannelIn<double> *output, ChannelIn<double> *writer_setpoint);
  virtual ~Step();

private:

  // Class variables
  double v_output;

  // Model objects
  XXStepModel::XXStepModel *myXXStepModel;
  Writer<double> *myw_output;
  Writer<double> *mywriter_d;

  // Model groups
  Parallel *myPARALLEL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
