/**
 * Source file for the JIWY model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "JIWY.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace JIWY { 

JIWY::JIWY(ChannelOut<double> *joystick_hor_in, ChannelOut<double> *joystick_vert_in, ChannelOut<double> *robot_hor_feedback, ChannelIn<uint16_t> *robot_hor_out, ChannelOut<double> *robot_ver_feedback, ChannelIn<uint16_t> *robot_ver_out) :
    Parallel(NULL)
{
  SETNAME(this, "JIWY");

  // Initialize channels
  myHorizontalcorr_to_VerticalcorrChannel = new UnbufferedChannel<double, One2In, Out2One>();
  myHorizontalout_to_Checkhor_check_inChannel = new UnbufferedChannel<double, One2In, Out2One>();
  myVerticalout_to_Checkvert_check_inChannel = new UnbufferedChannel<double, One2In, Out2One>();

  // Initialize model objects
  myCheck = new Check::Check(myHorizontalout_to_Checkhor_check_inChannel, robot_hor_out, myVerticalout_to_Checkvert_check_inChannel, robot_ver_out);
  SETNAME(myCheck, "Check");
  myHorizontal = new PositionControllerPan::PositionControllerPan(myHorizontalcorr_to_VerticalcorrChannel, joystick_hor_in, myHorizontalout_to_Checkhor_check_inChannel, robot_hor_feedback);
  SETNAME(myHorizontal, "Horizontal");
  myVertical = new PositionControllerTilt::PositionControllerTilt(myHorizontalcorr_to_VerticalcorrChannel, joystick_vert_in, myVerticalout_to_Checkvert_check_inChannel, robot_ver_feedback);
  SETNAME(myVertical, "Vertical");


  // Register model objects
  this->append_child(myHorizontal);
  this->append_child(myCheck);
  this->append_child(myVertical);

  // protected region constructor on begin
  // protected region constructor end
}

JIWY::~JIWY()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model objects
  delete myVertical;
  delete myHorizontal;
  delete myCheck;

  // Destroy channels
  delete myHorizontalcorr_to_VerticalcorrChannel;
  delete myHorizontalout_to_Checkhor_check_inChannel;
  delete myVerticalout_to_Checkvert_check_inChannel;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
