/**
 * Header file for the ChckHorCalc model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace JIWY { namespace Check { namespace ChckHorCalc { 

class ChckHorCalc : public CodeBlock
{

public:
  // Define constructor and destructor
  ChckHorCalc(uint32_t &hor_in, uint32_t &hor_out);
  virtual ~ChckHorCalc();
  void execute();

private:

  // Class variables
  uint32_t &hor_in;
  uint32_t &hor_out;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
