/**
 * Header file for the ChkVerCalc model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace JIWY { namespace Check { namespace ChkVerCalc { 

class ChkVerCalc : public CodeBlock
{

public:
  // Define constructor and destructor
  ChkVerCalc(uint32_t &ver_in, uint16_t &ver_out);
  virtual ~ChkVerCalc();
  void execute();

private:

  // Class variables
  uint32_t &ver_in;
  uint16_t &ver_out;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
