/**
 * Source file for the DisplayOutputs model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "DisplayOutputs.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace DisplayOutputs { 

DisplayOutputs::DisplayOutputs(ChannelOut<double> *steeringval_out, ChannelOut<double> *stetpoint_out) :
    Sequential(NULL)
{
  SETNAME(this, "DisplayOutputs");

  // Initialize model objects
  myDisplay = new Display::Display(setpoint, steerval);
  SETNAME(myDisplay, "Display");
  myread_setpoint = new Reader<double>(&setpoint, stetpoint_out);
  SETNAME(myread_setpoint, "read_setpoint");
  myread_steerval = new Reader<double>(&steerval, steeringval_out);
  SETNAME(myread_steerval, "read_steerval");

  // Create PARALLEL group
  myPARALLEL = new Parallel(
    (CSPConstruct *) myread_setpoint,
    (CSPConstruct *) myread_steerval,
    NULL
  );
  SETNAME(myPARALLEL, "PARALLEL");


  // Register model objects
  this->append_child(myPARALLEL);
  this->append_child(myDisplay);

  // protected region constructor on begin
  // protected region constructor end
}

DisplayOutputs::~DisplayOutputs()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete myPARALLEL;

  // Destroy model objects
  delete myread_steerval;
  delete myread_setpoint;
  delete myDisplay;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
