# build.mk file for Step.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libStep.a

Step/lib/libStep.a:
	@echo
	@echo "Building $@"
	@make -C Step --no-print-directory

lib/libStep.a: Step/lib/libStep.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libStep.a gets properly rebuild
Step/lib/libStep.a: Step/src/Step.cpp Step/include/Step/Step.h
Step/lib/libStep.a: Step/src/XXStepModel.cpp Step/include/Step/XXStepModel.h Step/include/Step/xxsim/StepModel.hpp

# protected region additional dependencies on begin
# protected region additional dependencies end