/**
 * Source file for the ChckHorCalc model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Check/ChckHorCalc.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace JIWY { namespace Check { namespace ChckHorCalc { 

ChckHorCalc::ChckHorCalc(double &hor_in, double &hor_out) :
    CodeBlock(), hor_in(hor_in), hor_out(hor_out)
{
  SETNAME(this, "ChckHorCalc");

  // protected region constructor on begin
  // protected region constructor end
}

ChckHorCalc::~ChckHorCalc()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end
}

void ChckHorCalc::execute()
{
  // protected region execute code on begin
  // protected region execute code end
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
