/**
 * Source file for the ChkVerCalc model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Check/ChkVerCalc.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace JIWY { namespace Check { namespace ChkVerCalc { 

ChkVerCalc::ChkVerCalc(uint32_t &ver_in, uint16_t &ver_out) :
    CodeBlock(), ver_in(ver_in), ver_out(ver_out)
{
  SETNAME(this, "ChkVerCalc");

  // protected region constructor on begin
  // protected region constructor end
}

ChkVerCalc::~ChkVerCalc()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end
}

void ChkVerCalc::execute()
{
  // protected region execute code on begin
  // protected region execute code end
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
