# build.mk file for PWMtester.archm, provide information to 'project MakeFile' 
# Generated by the TERRA Arch2LUNA generator version 1.0.0
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/PWMtester

PWMtester/PWMtester:
	@echo
	@echo "Building $@"
	@make -C PWMtester --no-print-directory

bin/PWMtester: PWMtester/PWMtester | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/PWMtester gets properly rebuild
PWMtester/PWMtester: PWMtester/src/main.cpp PWMTester/lib/libPWMTester.a
PWMtester/PWMtester: PWMtester/src/MainModel.cpp PWMtester/include/MainModel.h PWMTester/include/PWMTester/PWMTester.h

# protected region additional dependencies on begin
# protected region additional dependencies end