# build.mk file for PWMTester.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libPWMTester.a

PWMTester/lib/libPWMTester.a:
	@echo
	@echo "Building $@"
	@make -C PWMTester --no-print-directory

lib/libPWMTester.a: PWMTester/lib/libPWMTester.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libPWMTester.a gets properly rebuild
PWMTester/lib/libPWMTester.a: PWMTester/src/PWMTester.cpp PWMTester/include/PWMTester/PWMTester.h
PWMTester/lib/libPWMTester.a: PWMTester/src/Pcode.cpp PWMTester/include/PWMTester/Pcode.h

# protected region additional dependencies on begin
# protected region additional dependencies end