# build.mk file for LinearSystem.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libLinearSystem.a

LinearSystem/lib/libLinearSystem.a:
	@echo
	@echo "Building $@"
	@make -C LinearSystem --no-print-directory

lib/libLinearSystem.a: LinearSystem/lib/libLinearSystem.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libLinearSystem.a gets properly rebuild
LinearSystem/lib/libLinearSystem.a: LinearSystem/src/LinearSystem.cpp LinearSystem/include/LinearSystem/LinearSystem.h
LinearSystem/lib/libLinearSystem.a: LinearSystem/src/XXLinearSystemModel.cpp LinearSystem/include/LinearSystem/XXLinearSystemModel.h LinearSystem/include/LinearSystem/xxsim/LinearSystemModel.hpp

# protected region additional dependencies on begin
# protected region additional dependencies end