/**
 * Source file for the convert_vert model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "convert_vert.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace IO { namespace convert_vert { 

convert_vert::convert_vert(double &ver_input, uint16_t &ver_output) :
    CodeBlock(), ver_input(ver_input), ver_output(ver_output){
  SETNAME(this, "convert_vert");

  // protected region constructor on begin

  // protected region constructor end
}

convert_vert::~convert_vert()
{
  // protected region destructor on begin

  // protected region destructor end
}

void convert_vert::execute()
{
  // protected region execute code on begin

  // protected region execute code end
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
