/**
 * Source file for the convert_hor model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "convert_hor.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace IO { namespace convert_hor { 

convert_hor::convert_hor(double &hor_input, uint16_t &hor_output) :
    CodeBlock(), hor_input(hor_input), hor_output(hor_output){
  SETNAME(this, "convert_hor");

  // protected region constructor on begin

  // protected region constructor end
}

convert_hor::~convert_hor()
{
  // protected region destructor on begin

  // protected region destructor end
}

void convert_hor::execute()
{
  // protected region execute code on begin

  // protected region execute code end
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
