/**
 * Source file for the IO model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "IO.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace IO { 

IO::IO(ChannelOut<double> *hor_input, ChannelIn<uint16_t> *hor_output, ChannelOut<double> *ver_input, ChannelIn<uint16_t> *ver_output) :
    Parallel(NULL)
{
  SETNAME(this, "IO");

  // Initialize model objects
  myconvert_hor = new convert_hor::convert_hor(hor_input, hor_output);
  SETNAME(myconvert_hor, "convert_hor");
  myconvert_vert = new convert_vert::convert_vert(ver_input, ver_output);
  SETNAME(myconvert_vert, "convert_vert");
  myhor_input_reader = new Reader<double>(&hor_input, hor_input);
  SETNAME(myhor_input_reader, "hor_input_reader");
  myhor_output_writer = new Writer<uint16_t>(&hor_output, hor_output);
  SETNAME(myhor_output_writer, "hor_output_writer");
  myver_input_reader = new Reader<double>(&ver_input, ver_input);
  SETNAME(myver_input_reader, "ver_input_reader");
  myver_output_writer = new Writer<uint16_t>(&ver_output, ver_output);
  SETNAME(myver_output_writer, "ver_output_writer");

  // Create SEQUENTIAL group
  mySEQUENTIAL = new Sequential(
    (CSPConstruct *) myhor_input_reader,
    (CSPConstruct *) myconvert_hor,
    (CSPConstruct *) myhor_output_writer,
    NULL
  );
  SETNAME(mySEQUENTIAL, "SEQUENTIAL");

  // Create SEQUENTIAL1 group
  mySEQUENTIAL1 = new Sequential(
    (CSPConstruct *) myver_input_reader,
    (CSPConstruct *) myconvert_vert,
    (CSPConstruct *) myver_output_writer,
    NULL
  );
  SETNAME(mySEQUENTIAL1, "SEQUENTIAL1");


  // Register model objects
  this->append_child(mySEQUENTIAL);
  this->append_child(mySEQUENTIAL1);

  // protected region constructor on begin

  // protected region constructor end
}

IO::~IO()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin

  // protected region destructor end

  // Destroy model groups
  delete mySEQUENTIAL;
  delete mySEQUENTIAL1;

  // Destroy model objects
  delete myver_output_writer;
  delete myver_input_reader;
  delete myhor_output_writer;
  delete myhor_input_reader;
  delete myconvert_vert;
  delete myconvert_hor;
}



// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} 
