/**
 * Source file for the PositionControllerPan model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "PositionControllerPan.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace PositionControllerPan { 

PositionControllerPan::PositionControllerPan(ChannelIn<double> *corr, ChannelOut<double> *in, ChannelIn<double> *out, ChannelOut<double> *position) :
    Sequential(NULL)
{
  SETNAME(this, "PositionControllerPan");

  // Initialize model objects
  myXXPositionControllerPanModel = new XXPositionControllerPanModel::XXPositionControllerPanModel(v_corr, v_in, v_out, v_position);
  SETNAME(myXXPositionControllerPanModel, "XXPositionControllerPanModel");
  myr_in = new Reader<double>(&v_in, in);
  SETNAME(myr_in, "r_in");
  myr_position = new Reader<double>(&v_position, position);
  SETNAME(myr_position, "r_position");
  myw_corr = new Writer<double>(&v_corr, corr);
  SETNAME(myw_corr, "w_corr");
  myw_out = new Writer<double>(&v_out, out);
  SETNAME(myw_out, "w_out");

  // Create INS group
  myINS = new Parallel(
    (CSPConstruct *) myr_position,
    (CSPConstruct *) myr_in,
    NULL
  );
  SETNAME(myINS, "INS");

  // Create OUTS group
  myOUTS = new Parallel(
    (CSPConstruct *) myw_out,
    (CSPConstruct *) myw_corr,
    NULL
  );
  SETNAME(myOUTS, "OUTS");


  // Register model objects
  this->append_child(myINS);
  this->append_child(myXXPositionControllerPanModel);
  this->append_child(myOUTS);

  // protected region constructor on begin
  // protected region constructor end
}

PositionControllerPan::~PositionControllerPan()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete myINS;
  delete myOUTS;

  // Destroy model objects
  delete myw_out;
  delete myw_corr;
  delete myr_position;
  delete myr_in;
  delete myXXPositionControllerPanModel;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
