/**
 * Source file for the XXPositionControllerPanModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * 20-sim C++ glue code to connect to PositionControllerPanModel
 * Modifying this file is absolutely not recommended!
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "XXPositionControllerPanModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace PositionControllerPan { namespace XXPositionControllerPanModel { 

XXPositionControllerPanModel::XXPositionControllerPanModel(double &corr, double &in, double &out, double &position) :
    CodeBlock(), corr(corr), in(in), out(out), position(position){
  SETNAME(this, "XXPositionControllerPanModel");

  using namespace LUNA::xxsim;

  m_model = new PositionControllerPanModel;


  m_model->addInput(&position, XXVARIABLE, 6, 1, 1);


  m_model->addOutput(&out, XXVARIABLE, 7, 1, 1);


  m_model->addOutput(&corr, XXVARIABLE, 8, 1, 1);


  m_model->addInput(&in, XXVARIABLE, 9, 1, 1);


  m_model->start();
}

XXPositionControllerPanModel::~XXPositionControllerPanModel()
{
    m_model->stop();

	//@todo Clean up adapters

    delete m_model;
}

void XXPositionControllerPanModel::execute()
{
    m_model->step();
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
