# build.mk file for submodel.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libsubmodel.a

submodel/lib/libsubmodel.a:
	@echo
	@echo "Building $@"
	@make -C submodel --no-print-directory

lib/libsubmodel.a: submodel/lib/libsubmodel.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libsubmodel.a gets properly rebuild
submodel/lib/libsubmodel.a: submodel/src/submodel.cpp submodel/include/submodel/submodel.h
submodel/lib/libsubmodel.a: submodel/src/Pcode.cpp submodel/include/submodel/Pcode.h

# protected region additional dependencies on begin
# protected region additional dependencies end