/**
 * Header file for the PCode model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Producer { namespace PCode { 

class PCode : public CodeBlock
{

public:
  // Define constructor and destructor
  PCode(int &peer);
  virtual ~PCode();

  void execute();

private:

  // Class variables
  int &peer;

  // protected region additional class members or functions on begin
  int vars[3];
  bool initialize(void);
  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
