/**
 * Header file for the XXStepModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * 20-sim C++ glue code to connect to StepModel
 * Modifying this file is absolutely not recommended!
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
#include "xxsim/StepModel.hpp" 
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace Step { namespace XXStepModel { 

class XXStepModel : public CodeBlock
{

public:
  // Define constructor and destructor
  XXStepModel(double &output);
  virtual ~XXStepModel();

  void execute();

private:

  // Class variables
  double &output;

  StepModel *m_model;
};

// Close namespace(s)
} } 
