/**
 * Source file for the Consumer12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Consumer12.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Consumer12 { 



Consumer12::Consumer12(ChannelOut<bool> *cons_ch1) :
    Sequential(NULL)
{
  SETNAME(this, "Consumer12");

  // Initialize model objects
  mych1read = new Reader<bool>(&aVarable, cons_ch1);
  SETNAME(mych1read, "ch1read");


  // Register model objects
  this->append_child(mych1read);

  // protected region constructor on begin
  // protected region constructor end
}

Consumer12::~Consumer12()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model objects
  delete mych1read;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
