/**
 * Source file for the Display model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "DisplayOutputs/Display.h"
// protected region additional headers on begin
#include <string.h>
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace DisplayOutputs { namespace Display { 

Display::Display(double &setpoint, double &steerval) :
    CodeBlock(), setpoint(setpoint), steerval(steerval){
  SETNAME(this, "Display");

  // protected region constructor on begin
  // protected region constructor end
}

Display::~Display()
{
  // protected region destructor on begin
  // protected region destructor end
}

void Display::execute()
{
  // protected region execute code on begin
	printf("Display: Setpoint=%f\n", setpoint);
	printf("Display: Steering value=%f\n", steerval);

  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
