/**
 * Source file for the LinearSystem model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "LinearSystem.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace LinearSystem { 

LinearSystem::LinearSystem(ChannelOut<double> *u, ChannelIn<double> *y) :
    Sequential(NULL)
{
  SETNAME(this, "LinearSystem");

  // Initialize model objects
  myXXLinearSystemModel = new XXLinearSystemModel::XXLinearSystemModel(v_u, v_y);
  SETNAME(myXXLinearSystemModel, "XXLinearSystemModel");
  myr_u = new Reader<double>(&v_u, u);
  SETNAME(myr_u, "r_u");
  myw_y = new Writer<double>(&v_y, y);
  SETNAME(myw_y, "w_y");


  // Register model objects
  this->append_child(myXXLinearSystemModel);
  this->append_child(myw_y);
  this->append_child(myr_u);

  // protected region constructor on begin
  // protected region constructor end
}

LinearSystem::~LinearSystem()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model objects
  delete myw_y;
  delete myr_u;
  delete myXXLinearSystemModel;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
