/**
 * Source file for the Prullenbak model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Producer/Prullenbak.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Producer { namespace Prullenbak { 

Prullenbak::Prullenbak(int &peer) :
    CodeBlock(), peer(peer){
  SETNAME(this, "Prullenbak");

  // protected region constructor on begin
  // protected region constructor end
}

Prullenbak::~Prullenbak()
{
  // protected region destructor on begin
  // protected region destructor end
}

void Prullenbak::execute()
{
  // protected region execute code on begin
	printf("Garbage bin: %d\n", this->peer);
  // protected region execute code end
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } } 
