# build.mk file for Encoder_convert.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libEncoder_convert.a

Encoder_convert/lib/libEncoder_convert.a:
	@echo
	@echo "Building $@"
	@make -C Encoder_convert --no-print-directory

lib/libEncoder_convert.a: Encoder_convert/lib/libEncoder_convert.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libEncoder_convert.a gets properly rebuild
Encoder_convert/lib/libEncoder_convert.a: Encoder_convert/src/Encoder_convert.cpp Encoder_convert/include/Encoder_convert/Encoder_convert.h
Encoder_convert/lib/libEncoder_convert.a: Encoder_convert/src/encoderconvert.cpp Encoder_convert/include/Encoder_convert/encoderconvert.h

# protected region additional dependencies on begin
# protected region additional dependencies end