/**
 * Source file for the encoderconvert model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "encoderconvert.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace Encoder_convert { namespace encoderconvert { 

encoderconvert::encoderconvert(uint32_t &input, double &output) :
    CodeBlock(), input(input), output(output){
  SETNAME(this, "encoderconvert");

  // protected region constructor on begin
  // protected region constructor end
}

encoderconvert::~encoderconvert()
{
  // protected region destructor on begin
  // protected region destructor end
}

void encoderconvert::execute()
{
  // protected region execute code on begin
	this->output = scale(convert(this->input));
  // protected region execute code end
}

// protected region additional functions on begin
double encoderconvert::convert(uint32_t i)
{
	if(i < 0x80000000)
		return i;
	else
	{
		i = (i-1) ^ 0x7FFFFFFF;
		return -1*i;
	}
}

double encoderconvert::scale(double n)
{
	return n;
}
// protected region additional functions end

// Close namespace(s)
} } 
