/**
 * Source file for the XXPositionControllerTiltModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * 20-sim C++ glue code to connect to PositionControllerTiltModel
 * Modifying this file is absolutely not recommended!
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "XXPositionControllerTiltModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace PositionControllerTilt { namespace XXPositionControllerTiltModel { 

XXPositionControllerTiltModel::XXPositionControllerTiltModel(double &corr, double &in, double &out, double &position) :
    CodeBlock(), corr(corr), in(in), out(out), position(position){
  SETNAME(this, "XXPositionControllerTiltModel");

  using namespace LUNA::xxsim;

  m_model = new PositionControllerTiltModel;


  m_model->addOutput(&out, XXVARIABLE, 8, 1, 1);


  m_model->addInput(&corr, XXVARIABLE, 9, 1, 1);


  m_model->addInput(&in, XXVARIABLE, 10, 1, 1);


  m_model->addInput(&position, XXVARIABLE, 11, 1, 1);


  m_model->start();
}

XXPositionControllerTiltModel::~XXPositionControllerTiltModel()
{
    m_model->stop();

	//@todo Clean up adapters

    delete m_model;
}

void XXPositionControllerTiltModel::execute()
{
    m_model->step();
}

// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
