# build.mk file for mainModel.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.1
#
# protected region document description on begin

# protected region document description end

TARGETS+=bin/mainModel

mainModel/mainModel:
	@echo
	@echo "Building $@"
	@make -C mainModel --no-print-directory

bin/mainModel: mainModel/mainModel | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/mainModel gets properly rebuild
mainModel/mainModel: mainModel/src/main.cpp
mainModel/mainModel: mainModel/src/MainModel.cpp mainModel/include/MainModel.h
mainModel/mainModel: mainModel/src/Producer.cpp mainModel/include/Producer.h
mainModel/mainModel: mainModel/src/Producer/PCode.cpp mainModel/include/Producer/PCode.h
mainModel/mainModel: mainModel/src/consumer.cpp mainModel/include/consumer.h
mainModel/mainModel: mainModel/src/consumer/ch1Code.cpp mainModel/include/consumer/ch1Code.h
mainModel/mainModel: mainModel/src/consumer/ch2Code.cpp mainModel/include/consumer/ch2Code.h
mainModel/mainModel: mainModel/src/consumer/ch3Code.cpp mainModel/include/consumer/ch3Code.h

# protected region additional dependencies on begin

# protected region additional dependencies end