# build.mk file for Controller.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libController.a

Controller/lib/libController.a:
	@echo
	@echo "Building $@"
	@make -C Controller --no-print-directory

lib/libController.a: Controller/lib/libController.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libController.a gets properly rebuild
Controller/lib/libController.a: Controller/src/Controller.cpp Controller/include/Controller/Controller.h
Controller/lib/libController.a: Controller/src/XXControllerModel.cpp Controller/include/Controller/XXControllerModel.h Controller/include/Controller/xxsim/ControllerModel.hpp

# protected region additional dependencies on begin
# protected region additional dependencies end