/**
 * Source file for the Producer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Producer.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Producer { 



Producer::Producer(GuardedChannelIn<int> *ch1, GuardedChannelIn<int> *ch2, GuardedChannelIn<int> *ch3) :
    Sequential(NULL)
{
  SETNAME(this, "Producer");

  // Initialize model objects
  myPCode = new PCode::PCode(data);
  SETNAME(myPCode, "PCode");
  myw1 = new GuardedWriter<int>(&data, ch1);
  SETNAME(myw1, "w1");
  myw2 = new GuardedWriter<int>(&data, ch2);
  SETNAME(myw2, "w2");
  myw3 = new GuardedWriter<int>(&data, ch3);
  SETNAME(myw3, "w3");

  // Create ALTERNATIVE group
  myALTERNATIVE = new Alternative(
    true,
    (CSPConstruct *) myw1,
    (CSPConstruct *) myw2,
    (CSPConstruct *) myw3,
    NULL
  );
  SETNAME(myALTERNATIVE, "ALTERNATIVE");


  // Register model objects
  this->append_child(myPCode);
  this->append_child(myALTERNATIVE);

  // protected region constructor on begin

  // protected region constructor end
}

Producer::~Producer()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin

  // protected region destructor end

  // Destroy model groups
  delete myALTERNATIVE;

  // Destroy model objects
  delete myw3;
  delete myw2;
  delete myw1;
  delete myPCode;
}



// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
