# build.mk file for PositionControllerTilt.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libPositionControllerTilt.a

PositionControllerTilt/lib/libPositionControllerTilt.a:
	@echo
	@echo "Building $@"
	@make -C PositionControllerTilt --no-print-directory

lib/libPositionControllerTilt.a: PositionControllerTilt/lib/libPositionControllerTilt.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libPositionControllerTilt.a gets properly rebuild
PositionControllerTilt/lib/libPositionControllerTilt.a: PositionControllerTilt/src/PositionControllerTilt.cpp PositionControllerTilt/include/PositionControllerTilt/PositionControllerTilt.h
PositionControllerTilt/lib/libPositionControllerTilt.a: PositionControllerTilt/src/XXPositionControllerTiltModel.cpp PositionControllerTilt/include/PositionControllerTilt/XXPositionControllerTiltModel.h PositionControllerTilt/include/PositionControllerTilt/xxsim/PositionControllerTiltModel.hpp

# protected region additional dependencies on begin
# protected region additional dependencies end