# build.mk file for PositionControllerPan.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libPositionControllerPan.a

PositionControllerPan/lib/libPositionControllerPan.a:
	@echo
	@echo "Building $@"
	@make -C PositionControllerPan --no-print-directory

lib/libPositionControllerPan.a: PositionControllerPan/lib/libPositionControllerPan.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libPositionControllerPan.a gets properly rebuild
PositionControllerPan/lib/libPositionControllerPan.a: PositionControllerPan/src/PositionControllerPan.cpp PositionControllerPan/include/PositionControllerPan/PositionControllerPan.h
PositionControllerPan/lib/libPositionControllerPan.a: PositionControllerPan/src/XXPositionControllerPanModel.cpp PositionControllerPan/include/PositionControllerPan/XXPositionControllerPanModel.h PositionControllerPan/include/PositionControllerPan/xxsim/PositionControllerPanModel.hpp

# protected region additional dependencies on begin
# protected region additional dependencies end