/**
 * Source file for the Consumer12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Consumer12.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Consumer12 { 



Consumer12::Consumer12(ChannelOut<int> *cons_ch1, ChannelOut<int> *cons_ch2) :
    Recursion<CSPConstruct>()
{
  SETNAME(this, "Consumer12");

  // Initialize model objects
  myCCode = new CCode::CCode(aVarable, bVariable);
  SETNAME(myCCode, "CCode");
  mych1read = new Reader<int>(&aVarable, cons_ch1);
  SETNAME(mych1read, "ch1read");
  mych2read = new Reader<int>(&bVariable, cons_ch2);
  SETNAME(mych2read, "ch2read");

  // Create SEQUENTIAL group
  mySEQUENTIAL = new Sequential(
    (CSPConstruct *) mych1read,
    (CSPConstruct *) mych2read,
    NULL
  );
  SETNAME(mySEQUENTIAL, "SEQUENTIAL");

  // Create SEQUENTIAL_A group
  mySEQUENTIAL_A = new Sequential(
    (CSPConstruct *) mySEQUENTIAL,
    (CSPConstruct *) myCCode,
    NULL
  );
  SETNAME(mySEQUENTIAL_A, "SEQUENTIAL_A");

  // Register SEQUENTIAL_A as top-level recursive object
  setToActivate(mySEQUENTIAL_A);
  setEvaluateCondition(true);


  // protected region constructor on begin
  // protected region constructor end
}

Consumer12::~Consumer12()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete mySEQUENTIAL;
  delete mySEQUENTIAL_A;

  // Destroy model objects
  delete mych2read;
  delete mych1read;
  delete myCCode;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} } 
