# build.mk file for prod_cons_DF.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.1
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/prod_cons_DF

prod_cons_DF/prod_cons_DF:
	@echo
	@echo "Building $@"
	@make -C prod_cons_DF --no-print-directory

bin/prod_cons_DF: prod_cons_DF/prod_cons_DF | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/prod_cons_DF gets properly rebuild
prod_cons_DF/prod_cons_DF: prod_cons_DF/src/main.cpp
prod_cons_DF/prod_cons_DF: prod_cons_DF/src/MainModel.cpp prod_cons_DF/include/MainModel.h
prod_cons_DF/prod_cons_DF: prod_cons_DF/src/Producer12.cpp prod_cons_DF/include/Producer12.h
prod_cons_DF/prod_cons_DF: prod_cons_DF/src/Consumer12.cpp prod_cons_DF/include/Consumer12.h

# protected region additional dependencies on begin
# protected region additional dependencies end