/**
 * Header file for the Joystick model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "x_code.h"
#include "y_code.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace Joystick { 

class Joystick : public Parallel
{

public:
  // Define constructor and destructor
  Joystick(ChannelIn<double> *joystick_hor, ChannelIn<double> *joystick_ver);
  virtual ~Joystick();

private:

  // Class variables
  double x;
  double y;

  // Model objects
  x_code::x_code *myx_code;
  Writer<double> *myx_writer;
  y_code::y_code *myy_code;
  Writer<double> *myy_writer;

  // Model groups
  Sequential *mySEQUENTIAL;
  Sequential *mySEQUENTIAL1;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
