/**
 * Header file for the Controller model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "XXControllerModel.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace Controller { 

class Controller : public Sequential
{

public:
  // Define constructor and destructor
  Controller(ChannelOut<double> *MV, ChannelOut<double> *SP, ChannelIn<double> *output, ChannelIn<double> *steervalue);
  virtual ~Controller();

private:

  // Class variables
  double v_MV;
  double v_SP;
  double v_output;

  // Model objects
  XXControllerModel::XXControllerModel *myXXControllerModel;
  Reader<double> *myr_MV;
  Reader<double> *myr_SP;
  Writer<double> *myw_output;
  Writer<double> *mywriter1;

  // Model groups
  Parallel *myINS;
  Parallel *myPARALLEL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
