/**
 * Header file for the XXControllerModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * 20-sim C++ glue code to connect to ControllerModel
 * Modifying this file is absolutely not recommended!
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
#include "xxsim/ControllerModel.hpp" 
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace Controller { namespace XXControllerModel { 

class XXControllerModel : public CodeBlock
{

public:
  // Define constructor and destructor
  XXControllerModel(double &MV, double &SP, double &output);
  virtual ~XXControllerModel();

  void execute();

private:

  // Class variables
  double &MV;
  double &SP;
  double &output;

  ControllerModel *m_model;
};

// Close namespace(s)
} } 
