/**
 * Source file for the Pcode model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Pcode.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace PWMTester { namespace Pcode { 

Pcode::Pcode(uint16_t &test) :
    CodeBlock(), test(test){
  SETNAME(this, "Pcode");

  // protected region constructor on begin
  // protected region constructor end
}

Pcode::~Pcode()
{
  // protected region destructor on begin
  // protected region destructor end
}

void Pcode::execute()
{
  // protected region execute code on begin
	int16_t t;


	//t = -32768; // fast reverse
	t = 32767; // fast forward
	//t = 0; // stop
	//t = -1000; // deadzone?

	//this->test = (uint16_t) t;
	this->test = convert(t);
  // protected region execute code end
}

// protected region additional functions on begin
uint16_t Pcode::convert(int16_t n)
{
	if(n>=0 && n<32768)
		return n|0x8000;
	else if(n >= -32768)
		return (n^0xFFFF) + 1;
	else
		return 0;
}

// protected region additional functions end

// Close namespace(s)
} } 
