/**
 * Header file for the DisplayOutputs model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "DisplayOutputs/Display.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace DisplayOutputs { 

class DisplayOutputs : public Sequential
{

public:
  // Define constructor and destructor
  DisplayOutputs(ChannelOut<double> *steeringval_out, ChannelOut<double> *stetpoint_out);
  virtual ~DisplayOutputs();

private:

  // Class variables
  double setpoint;
  double steerval;

  // Model objects
  Display::Display *myDisplay;
  Reader<double> *myread_setpoint;
  Reader<double> *myread_steerval;

  // Model groups
  Parallel *myPARALLEL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
