# build.mk file for EncoderTester.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libEncoderTester.a

EncoderTester/lib/libEncoderTester.a:
	@echo
	@echo "Building $@"
	@make -C EncoderTester --no-print-directory

lib/libEncoderTester.a: EncoderTester/lib/libEncoderTester.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libEncoderTester.a gets properly rebuild
EncoderTester/lib/libEncoderTester.a: EncoderTester/src/EncoderTester.cpp EncoderTester/include/EncoderTester/EncoderTester.h
EncoderTester/lib/libEncoderTester.a: EncoderTester/src/Pcode.cpp EncoderTester/include/EncoderTester/Pcode.h

# protected region additional dependencies on begin
# protected region additional dependencies end