# build.mk file for EncoderTester.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin

# protected region document description end

TARGETS+=lib/libencodertestersubmodel.a

EncoderTester/lib/libencodertestersubmodel.a:
	@echo
	@echo "Building $@"
	@make -C EncoderTester --no-print-directory

lib/libencodertestersubmodel.a: EncoderTester/lib/libencodertestersubmodel.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libencodertestersubmodel.a gets properly rebuild
EncoderTester/lib/libencodertestersubmodel.a: EncoderTester/src/encodertestersubmodel.cpp EncoderTester/include/encodertestersubmodel/encodertestersubmodel.h
EncoderTester/lib/libencodertestersubmodel.a: EncoderTester/src/Pcode.cpp EncoderTester/include/encodertestersubmodel/Pcode.h

# protected region additional dependencies on begin

# protected region additional dependencies end