# build.mk file for Encodertester.archm, provide information to 'project MakeFile' 
# Generated by the TERRA Arch2LUNA generator version 1.0.0
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/Encodertester

Encodertester/Encodertester:
	@echo
	@echo "Building $@"
	@make -C Encodertester --no-print-directory

bin/Encodertester: Encodertester/Encodertester | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/Encodertester gets properly rebuild
Encodertester/Encodertester: Encodertester/src/main.cpp EncoderTester/lib/libEncoderTester.a
Encodertester/Encodertester: Encodertester/src/MainModel.cpp Encodertester/include/MainModel.h EncoderTester/include/EncoderTester/EncoderTester.h

# protected region additional dependencies on begin
# protected region additional dependencies end